#!/usr/bin/env bash
# World wide web

func ()
{
	dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | awk -v var="$1" 'NR==2{print "The subdomain", var, "is a", $4, "record and points to", $5 }'
}

if [ "$#" -eq 1 ];
then
	func "www" "$1"
 	func "lb-01" "$1"
	func "web-01" "$1"
	func "web-02" "$1"
else
	func "$2" "$1"
fi
