#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;
	location /redirect_me {
		 return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}" > /etc/nginx/sites-available/default
service nginx start
