#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html

printf %s "server {
	listen 80;
	listen [::]:80;

	server_name example.com;

	root /usr/share/nginx/html;
	index index.html;

	location /redirect_me {
		 return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}" > /etc/nginx/sites-available/default

sudo service nginx start