#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /usr/share/nginx/html;
      internal;
    }

    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default
service nginx restart
