#!/usr/bin/env bash
# create a file
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT SIGTERM
while :
      do
	    echo To infinity and beyond
	    sleep 2
done
