#!/usr/bin/env bash
# create a file
echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill'; rm /var/run/holbertonscript.pid" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT
while :
      do
	    echo To infinity and beyond
	    sleep 2
done
