#!/usr/bin/env bash
# script that displays numbers from 1 to 100.
for i in {1..100};
do
    x=$((i % 3))
    y=$((i % 5))
    if [ $x -eq 0 ] && [ $y -eq 0 ]
    then
	echo FizzBuzz

    elif [ $x -eq 0 ]
    then
	echo Fizz

    elif [ $y -eq 0 ]
    then
	echo Buzz

    else
	echo $i

    fi

done
